config/routes.rb
  scope 'admin', :as => 'scrumbler_admin' do                                            
    post '/scrumbler/points_field', :as => 'update_points_field', :controller => 'scrumbler_admins', :action => 'update_points_field', :format => false
    put '/scrumbler/points_field', :as => 'update_points_field', :controller => 'scrumbler_admins', :action => 'update_points_field', :format => false
    match '/scrumbler/:tab' => 'scrumbler_admins#index', :as => nil, :format => false
  end    

  match '/scrumbler/admin' => "scrumbler_admins#index"

  match '/projects/:project_id/scrumbler_backlogs/create_issue' => 'scrumbler_backlogs#create_issue', :format => false, :as => 'project_scrumbler_backlogs_new_issue'

  resources :projects do
    resource :scrumbler_backlogs, :only => [:show] do
      member do
        post :update_scrum_points
        post :change_issue_version
        post :select_sprint
        post :create_version
        post :open_sprint 
        post :new_issue
        get  :new_issue
        post :move_issue_priority 
      end
      # could not create into resource block, move out until a better idea
      # match 'create_issue' => 'scrumbler_backlogs#create_issue', :format => false, :as => 'new_issue', :on => :collection
    end
    
    resource "scrumbler", :controller => 'scrumbler' do
      member do
        get '/index' => 'scrumbler#index'
        post :sprint
      end
    end

    resource :scrumbler_settings, :only => [:show] do
      member do
        post :update_trackers 
        post :update_issue_statuses
      end
    end
    match 'scrumbler_settings/:tab' => 'scrumbler_settings#show', :tab => nil, :as => 'scrumbler_settings', :format => false

    resources :scrumbler_sprints do
      member do
        post :update_general
        post :update_trackers
        post :update_issue_statuses
        get :burndown
        post :close_confirm
        get :settings
      end
      get  'settings/:tab' => 'scrumbler_sprints#settings', :tab => 'general', :as => 'settings', :format => false
      post 'issue/:issue_id' => 'scrumbler_sprints#update_issue', :as => 'update_issue'
      post 'issue/:issue_id/change_assignment_to_me' => 'scrumbler_sprints#change_issue_assignment_to_me', :format => false
      post 'issue/:issue_id/drop_issue_assignment' => 'scrumbler_sprints#drop_issue_assignment', :as => 'drop_issue_assignment', :format => false
    end

  end

app/controllers/scrumbler_controller.rb
# Scrumbler - Add scrum functionality to any Redmine installation
# Copyright (C) 2011 256Mb Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class ScrumblerController < ScrumblerAbstractController
  unloadable

  before_filter :authorize, :only => [:sprint, :index]
  
  def index
    @scrumbler_sprint = ScrumblerSprint.find_by_id(params[:scrumbler_sprint_id])
    
    @show_all = if @scrumbler_sprint && @scrumbler_sprint.status != ScrumblerSprint::OPENED
      true
    else
      !!params[:show_all]
    end

    @scrumbler_sprints  = @show_all ? @project.scrumbler_sprints : @project.scrumbler_sprints.opened
    @scrumbler_sprint ||= @scrumbler_sprints.last
  end
    
  def sprint
    @sprint = @project.scrumbler_sprints.find(params[:sprint_id])
    render :update do |page|
      page.replace_html 'scrumbler_sprint', :partial => 'sprint', :object => @sprint
    end
  end
  
end

app/helpers/scrumbler_helper.rb
# Scrumbler - Add scrum functionality to any Redmine installation
# Copyright (C) 2011 256Mb Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
module ScrumblerHelper
  def scrumbler_javascript_helper
    # This Hack fir compability with  "Redmine - Stuff To Do Plugin".
    # That guys transform array to hash in this place.
    prepare_stupid_hash = Proc.new {|name|
      data = t(name)
      data = data.values if data.is_a?(Hash)
      data
    }

    translations = {
      :nodata => t(:label_no_data),
      :highstock => {
        :months => prepare_stupid_hash.call("date.month_names").compact,
        :shortMonths => prepare_stupid_hash.call("date.abbr_month_names").compact,
        :weekdays => prepare_stupid_hash.call("date.day_names").compact
      }
    }
    
    convert_translation = Proc.new {|key|  }
    
    %w(label_sort_lower
       label_sort_higher
       label_sort_highest
       label_sort_lowest 
       scrumbler_sprint 
       label_backlog 
       label_new_sprint 
       issue_not_assigned
       scrumbler_statistics
       label_header_error
       label_confirm_sprint_opening).each {|key| 
         key = key.to_sym
         translations[key] = t(key)
       }
    
    
    javascript_tag "var Scrumbler = {}; Scrumbler.Translations = #{translations.to_json}; Scrumbler.root_url = '../../'; Scrumbler.possible_points = #{ScrumblerIssueCustomField.points.possible_values.to_json};"
  end

  def prepare_issue_subject(issue)
    subj = issue.subject
    if issue.children?
      subj << "<hr>"
      issue.children.each {|child|
        link = "<a href=\"#{url_for({:controller => 'issues', :action => 'show', :id => child.id})}\" class=\"#{child.css_classes}\" title=\"#{child.subject[0..99]} (#{child.status.name})\">##{child.tracker.name} #{child.id}</a>"

        # link_to("##{child.tracker.name} #{child.id}", url_for({:controller => 'issues', :action => 'show', :id => child.id}),
        # :class => child.css_classes,
        # :title => "#{child.subject[0..99]} (#{child.status.name})")
        subj << "#{link}: #{child.subject} <br>"
      }
    end
    subj
  end

  def select_color_tag(name, value=nil, options={})
    out = hidden_field_tag(name, value, options)
    out << javascript_tag("new TinyColorChooser(\"#{sanitize_to_id(name)}\", #{options.to_json})");
  end

  def issue_for_json(issue)
    out = {
      :id => issue.id,
      :status_id => issue.status_id,
      :tracker_id => issue.tracker_id,
      :project_id => issue.project_id,
      :subject => prepare_issue_subject(issue),
      :points => issue.scrumbler_points,
      :closed => issue.closed?
    }
    out[:assigned_to] = {:id   => issue.assigned_to_id, :name => issue.assigned_to.name } if issue.assigned_to

    out
  end
  



  def prepare_issue_statuses(issue_statuses_settings, issue_statuses)
    r_issue_statuses = {}
    issue_statuses_settings.each{|id,issue_setting|
      _status = issue_statuses.detect {|status| status.id == id.to_i}
      r_issue_statuses[id.to_i] = issue_setting.merge({
        :status_id => id.to_i,
        :closed =>  _status.try(:is_closed),
        :name => _status.try(:name)
      })
    }
    r_issue_statuses
  end

  def prepare_trackers(trackers_settings, trackers)
    r_trackers = {}
    trackers_settings.each{|id,tracker_setting|
      r_trackers[id.to_i]=tracker_setting.merge({:name => trackers.detect {|tracker| tracker.id == id.to_i}.try(:name)})
    }
    r_trackers
  end

  def draw_scrumbler_dashboard(sprint)
    div_id = "dashboard_for_sprint_#{sprint.id}"
    prepared_issues = sprint.issues.sort(){|a,b| sprint.trackers[a.tracker_id.to_s][:position].to_i <=> sprint.trackers[b.tracker_id.to_s][:position].to_i }.map {|issue| issue_for_json(issue) }
    config = {
      :sprint => sprint,
      :name => sprint.name,
      :project => sprint.project,
      :statuses => prepare_issue_statuses(sprint.issue_statuses, IssueStatus.all),
      :trackers => prepare_trackers(sprint.trackers, sprint.project.trackers),
      :issues => prepared_issues,
      :url => project_url(sprint.project),
      :current_user_id => User.current.id
    }.to_json
    out = content_tag('div', '&nbsp;', {:style => "width:100%; height: 100%;"})
    out = "<div id='#{div_id}' style='width:100%;height:100%;'>&nbsp;</div>"
    out << javascript_tag("new Scrumbler.ScrumblerDashboard('#{div_id}', #{config});")
  end

  def select_sprint_statuses_tag(name, selected)
    select_tag name, options_for_select(ScrumblerSprint::STATUSES.collect {|s| [l("scrumbler_sprint_#{s}"), s]}, selected)
  end
end

app/views/scrumbler/_sprint.erb
<div id="scrumbler_sprint" style="">
	<% if sprint %>
	<% unless sprint.statistics_available?%>
	<div class="nodata">
		<%= t(:scrumbler_sprint_statistics_not_available)%>
	</div>
	<%end%>
	<div class="contextual">
		<%= link_to l(:label_statistics), burndown_project_scrumbler_sprint_path(@project, sprint), :class=> "icon icon-scrumbler-burndown" if sprint.statistics_available? %>
		<%= link_to l(:label_sprint_settings), project_scrumbler_sprint_settings_path(@project, sprint, 'general'), :class=> "icon icon-scrumbler-settings" if authorize_for(:scrumbler_sprints, :settings)%>
                <%=  %>
	</div>
	<%= raw draw_scrumbler_dashboard(sprint) %>
	<% else %>
	<p id="errorExplanation">
		<%= l :error_sprint_not_found_in_project %>
	</p>
	<% end %>
</div>

app/views/scrumbler/index.html.erb
<% content_for :header_tags do %>
	<%= stylesheet_link_tag    'scrumbler', :plugin => 'redmine_scrumbler' %>
	<%= javascript_include_tag 'Growler-packed', :plugin => 'redmine_scrumbler' %>
	<%= javascript_include_tag 'growler', :plugin => 'redmine_scrumbler' %>
	<%= scrumbler_javascript_helper %>
	<%= javascript_include_tag 'scrumbler-common', :plugin => 'redmine_scrumbler' %>
	<%= javascript_include_tag 'scrumbler-dashboard', :plugin => 'redmine_scrumbler' %>
<% end %>
<div class="contextual">
	<%= link_to_if_authorized l(:label_backlog), 
	{:controller => :scrumbler_backlogs,
	:action => :show, 
	:project_id => @project}, :class => "icon icon-scrumbler-backlog" %>
	
	<%= link_to_if_authorized l(:label_settings), 
	{:controller => :scrumbler_settings,
	:action => :show, 
	:project_id => @project}, :class => "icon icon-scrumbler-settings"  %>
</div>
<h2><%= l(:scrumbler_menu)%></h2>

<div id="scrumbler_dashboard">
	<% if @scrumbler_sprints.any? %>
		<p>
			<%= label_tag :scrumbler_sprint_id, l(:scrumbler_sprint) %>
	
			<%= collection_select "scrumbler_sprint", :id, @scrumbler_sprints, :id, :name,
			{
			:selected => @scrumbler_sprint.id
			},
			{
			:onchange => remote_function(:method=>:post,
			:url => {
			:controller => :scrumbler,
			:action => :sprint,
			:project_id => @project
			}, :with => "'sprint_id='+value")
			}%>
		</p>
		<p>
			<%if @show_all %>
				<%= link_to l(:show_opened), :controller => :scrumbler, :action => :index, :project_id => @project %>
			<%else%>
				<%= link_to l(:show_all), :controller => :scrumbler, :action => :index, :project_id => @project, :show_all => "" %>
			<%end%>
		</p>
		<%= render :partial => 'sprint', :object =>  @scrumbler_sprint %>
	<% else %>
		<%= link_to l(:show_all), :controller => :scrumbler, :action => :index, :project_id => @project, :show_all => "" %>
		<p class="nodata">
			<%= l(:versions_for_sprints_not_created) %>
		</p>
		<p class="nodata">
			<%= l(:label_no_data) %>
		</p>
	<% end %>
</div>